### ISSUE TITLE
"message": "Upsss... Something went wrong on server"

### ISSUE THREAD

**Issue by mdestafadilah** [mimamch/wa-gateway#14]
habis di update gak bisa kirim pak

**Comment by mimamch** [comment]
Bisa share detail request endpoint nya?

**Comment by mdestafadilah** [comment]
{{url}}/send-message

```bash
{
	"session": "notifprima1v3",
	"to": "623898973731",
	"text": "Hallo desta"
}
```

**Comment by mimamch** [comment]
Coba sementara sambil di console.log di blok catch nya supaya terlihat errornya di bagian mana...

**Comment by mdestafadilah** [comment]
hanya endpoint `/send-message` yang gak bisa pak. sebelumya bisa kok

<img width="426" alt="18-07-2023 08-53-25" src="https://github.com/mimamch/wa-gateway/assets/5575882/3f2b634a-fd8e-44c0-a4d1-c0b5cf20bf52">

btw kok aneh pak, padahal itu nomor saya, buat wa juga, kyknya pengecekan nomor wa atau bukan ada salah deh

**Comment by mimamch** [comment]
Coba perhatikan nomor teleponnya, seharusnya 62823, bukan langsung 623xxxx

**Comment by mdestafadilah** [comment]
wah iya pak, hehe.... tp lama pak, kok sampe 12s yak. saya close issue ya pak, makasih.
