### ISSUE TITLE
bermasalah di VPS

### ISSUE THREAD

**Issue by 94maldini** [mimamch/wa-gateway#22]
saya menjalankan [wa-gateway](https://github.com/mimamch/wa-gateway) ini di vps tapi ada masalah,  setelah GET /start-session?session=558822&scan=true  muncul log seperti ini
```shell
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
connecting =>  558822
disconnected =>  558822
``` 
langsung menghubungkan session 558822 tampa scan qr dengan keadaan folder wa_credentials kosong tidak ada session samasekali, dan saya test GET /send-message?to=081xxxxxxx&text=maldini%20test%20api%202&session=558822 muncul error seperti ini 
```shell
TypeError: Right-hand side of 'instanceof' is not an object
    at errorHandlerMiddleware (/root/nodejs/apiWa/app/middlewares/error_middleware.js:9:13)
    at Layer.handle_error (/root/nodejs/apiWa/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/nodejs/apiWa/node_modules/express/lib/router/index.js:326:13)
    at /root/nodejs/apiWa/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/root/nodejs/apiWa/node_modules/express/lib/router/index.js:346:12)
    at Immediate.next (/root/nodejs/apiWa/node_modules/express/lib/router/index.js:280:10)
    at Immediate.<anonymous> (/root/nodejs/apiWa/node_modules/express/lib/router/index.js:646:15)
    at process.processImmediate (node:internal/timers:478:21)
``` 
saya menjalankan VPS ubuntu-22.04-x86_64, nodejs versi v18.17.1
tapi saya jalankan di localhost windows jadi berjalan dengan normal

**Comment by mimamch** [comment]
sepertinya ada duplikat dengan session ID yang sudah ada: 558822, apakah sudah dicoba dengan session ID yang berbeda?

**Comment by 94maldini** [comment]
> sepertinya ada duplikat dengan session ID yang sudah ada: 558822, apakah sudah dicoba dengan session ID yang berbeda?

biar id baru tetap sama sudah bikin id baru 4x tetap sama

**Comment by mimamch** [comment]
dari error "TypeError: Right-hand side of 'instanceof' is not an object" itu sepertinya depedency wa-multi-session bukan versi terbaru, bisa coba dimulai dengan npm install dahulu

**Comment by 94maldini** [comment]
sudah npm install wa-multi-session@latest tapi tetap kembali ke 2.1.0 
```shell
# npm audit report

protobufjs  6.10.0 - 7.2.3
Severity: high
protobufjs Prototype Pollution vulnerability - https://github.com/advisories/GHSA-h755-8qp9-cq85
fix available via `npm audit fix --force`
Will install wa-multi-session@3.2.1, which is a breaking change
node_modules/protobufjs
  @adiwajshing/baileys  >=3.0.0
  Depends on vulnerable versions of protobufjs
  node_modules/@adiwajshing/baileys
    wa-multi-session  <=2.1.0
    Depends on vulnerable versions of @adiwajshing/baileys
    node_modules/wa-multi-session

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
``` 
dan sudah lakukan npm audit fix --force tetap ke 2.1.0 bukan ke 3.2.0, sudah lakukan hapus package-lock.json dan update dependencies "wa-multi-session": "3.2.0" tetap kembali 2.1.0

**Comment by mimamch** [comment]
Bisa dicoba untuk clone ulang repositorynya

**Comment by 94maldini** [comment]
masih 
```shell
APP IS RUNNING ON PORT 5001
connecting =>  cloudwa
GET /start-session?session=cloudwa&scan=true - - ms - -
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  cloudwa
connecting =>  aefdewaewf
connecting =>  aefdewaewf
connecting =>  cloudwa
disconnected =>  aefdewaewf
disconnected =>  cloudwa
``` 
server saya bermasalah atau apa sampai bisa begini

**Comment by Cloud-Dark** [comment]
1. coba gunakan repo terbaru
2. coba gunakan nodejs versi 16
3. coba atur dir seperti ini
![image](https://github.com/mimamch/wa-gateway/assets/28920412/1382f0bc-350e-4e0e-80f0-993c1174a690)

**Comment by 94maldini** [comment]
> 1. coba gunakan repo terbaru
> 2. coba gunakan nodejs versi 16
> 3. coba atur dir seperti ini
>    ![image](https://user-images.githubusercontent.com/28920412/260321922-1382f0bc-350e-4e0e-80f0-993c1174a690.png)

Ok sudah berhasil. Trimakasih
