### ISSUE TITLE
kirim pesan ke grup

### ISSUE THREAD

**Issue by jenilutfifauzi** [mimamch/wa-gateway#25]
apakah bisa kirim pesan ke grup bang?

klo boleh tau ini pake library apa?

**Comment by mdestafadilah** [comment]
izin jawab ya, kyaknya ini API sederhana aja deh, dan belum ada fiturenya, kali diliat [sini](https://github.com/mimamch/wa-gateway/blob/08db8eb6a67e29fd6af16e9931683de66a532029/utils/process-number.js#L3)  kalo core library pake [baileys](https://github.com/mimamch/wa-multi-session/blob/39061ca5c7fa998572a80cbf77c2a571caf221b9/package.json#L20), tp pak imam udah permudah  penggunaan baileys dengan buat library [wa-multi-session](https://github.com/mimamch/wa-multi-session/tree/master).

**Comment by jenilutfifauzi** [comment]
oh gabisa berarti ya

**Comment by jenilutfifauzi** [comment]
boleh saya bantu

**Comment by mdestafadilah** [comment]
> boleh saya bantu

oke pak, ditunggu ya PR nyah, saya belum sempet ngulik lagi ne library pak imam.

**Comment by mimamch** [comment]
bisa dikirimkan parameter isGroup: true dan tujuan menjadi id grup

**Comment by jenilutfifauzi** [comment]
cara mengetahui id group itu dimana ya bang?

**Comment by mdestafadilah** [comment]
> bisa dikirimkan parameter isGroup: true dan tujuan menjadi id grup

tolong update di readme.md pak informasinya, mksh.

**Comment by mdestafadilah** [comment]
> cara mengetahui id group itu dimana ya bang?

bisa pake cara ini pak https://www.youtube.com/watch?v=Vx53spbt_qk

**Comment by mimamch** [comment]
> cara mengetahui id group itu dimana ya bang?

coba kirim chat di grup tersebut, lalu di console.log maka akan muncul jid nya

**Comment by jenilutfifauzi** [comment]
> 

yang di console.lognya apa bang

**Comment by mimamch** [comment]
pada library ini [wa-multi-session](https://github.com/mimamch/wa-multi-session) ada fungsi onMessageReceived yang menyediakan parameter info dari pesan yang masuk. silahkan di console.log pesan masuk tersebut dan pada bagian key ada property jid grup nya

**Comment by jenilutfifauzi** [comment]
oh bikin function baru ya

**Comment by mdestafadilah** [comment]
```bash
{
	"session": "notifprima2v3",
	"isGroup": true,
	"to": "628XXX0281712-143XXX42XXX6",
	"text": "halo test dari service wa"
}
```

```bash
{
	"session": "notifprima2v3",
	"isGroup": true,
	"to": "628XXX0281712-143XXX42XXX6@g.us",
	"text": "halo test dari service wa"
}
```

sepertinya ada yang aneh pak, udah di buat true, beraakhir dengan message ini.

```bash
{
	"message": "Upsss... Something went wrong on server"
}
```

sudah dicoba pak?

**Comment by jenilutfifauzi** [comment]
<img width="487" alt="image" src="https://github.com/mimamch/wa-gateway/assets/61114044/d05dad18-5771-4a38-a24f-e2094fe37f45">

bang kenapa ya setiap bberapa jam suka kaya gini

**Comment by jenilutfifauzi** [comment]
> ```shell
> @g.us"
> ```

jgan pake @g.us
pake remoteJID

**Comment by mdestafadilah** [comment]
> 



> > ```shell
> > @g.us"
> > ```
> 
> jgan pake @g.us pake remoteJID

berhasil?

**Comment by jenilutfifauzi** [comment]
> 

berhasil

**Comment by rinomnurbdg** [comment]
![image](![WA](https://github.com/mimamch/wa-gateway/assets/11434134/63f9ed63-3924-4154-a2e9-6426b54f9930))

kenapa yah padahal dah make JID yang benar

**Comment by mimamch** [comment]
coba di log error nya apa

**Comment by jenilutfifauzi** [comment]
MA

> bisa dikirimkan parameter isGroup: true dan tujuan menjadi id grup

Mas klo ngirim ke Komunitas di WA itu bisa ga ya?

**Comment by mdestafadilah** [comment]
> ![WA](https://user-images.githubusercontent.com/11434134/263646286-d33b609b-5e8c-4773-af17-d930d69ab071.png)
> 
> kenapa yah padahal dah make JID yang benar

pak @jenilutfifauzi bisa di bantu, parameternya via postman?

**Comment by jenilutfifauzi** [comment]
> > ![WA](https://user-images.githubusercontent.com/11434134/263646286-d33b609b-5e8c-4773-af17-d930d69ab071.png)
> > kenapa yah padahal dah make JID yang benar
> 
> pak @jenilutfifauzi bisa di bantu, parameternya via postman?

<img width="842" alt="image" src="https://github.com/mimamch/wa-gateway/assets/61114044/ba430a16-e02b-40cb-8431-0f201b0c44d3">
kaya gini

**Comment by mdestafadilah** [comment]
kok remoteJID nyah beda ya, itu group baru ya pak @jenilutfifauzi ?

**Comment by jenilutfifauzi** [comment]
iya grup baruu

**Comment by rinomnurbdg** [comment]
remote Jid nya ko beda format yah ... kalo yang saya coba itu kan nomerpembuat_idgroup@g.us gitu kan yah ... saya coba browse group id disalahsatu penyedia wa blast keluar id groupnya seperti itu ? apakah beda dengan format dengan aplikasi wa api ini ya ? bisa dijelaskan cara ambil remote Jid supaya sesuai dengan req api ini ?
Terima kasih

**Comment by mdestafadilah** [comment]
> remote Jid nya ko beda format yah ... kalo yang saya coba itu kan [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) gitu kan yah ... saya coba browse group id disalahsatu penyedia wa blast keluar id groupnya seperti itu ? apakah beda dengan format dengan aplikasi wa api ini ya ? bisa dijelaskan cara ambil remote Jid supaya sesuai dengan req api ini ? Terima kasih

mohon di follow up pak imam @mimamch sedikit aneh, apakah @s.whatsapp.net atau @g.us ya

**Comment by mimamch** [comment]
untuk kirim ke grup betul ini ya : nomerpembuat_idgroup@g.us
bisa dicek remoteJid nya saat menerima pesan masuk di grup

**Comment by mdestafadilah** [comment]
> untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup

sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...

**Comment by jenilutfifauzi** [comment]
> > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> 
> sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...

pake service WA yang lain gimana maksudnya?

tinggal di console log fungsi yang pak @mimamch terangkan diatas, pake yang remoteJID
<img width="418" alt="image" src="https://github.com/mimamch/wa-gateway/assets/61114044/9cc64cf3-45d5-41b5-af65-d9af0da0392d">

**Comment by mdestafadilah** [comment]
> > > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> > 
> > 
> > sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...
> 
> pake service WA yang lain gimana maksudnya?
> 
> tinggal di console log fungsi yang pak @mimamch terangkan diatas, pake yang remoteJID <img alt="image" width="418" src="https://user-images.githubusercontent.com/61114044/263925282-9cc64cf3-45d5-41b5-af65-d9af0da0392d.png">

saya ada wa-gateway juga yang kirim ke group pake @g.us bisa ke kirim, karena groupnya defaultnya itu nomorpembuat_idgroup@g.us bukan yang format sekarang, yg pak @jenilutfifauzi test

**Comment by jenilutfifauzi** [comment]
> > > > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> > > 
> > > 
> > > sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...
> > 
> > 
> > pake service WA yang lain gimana maksudnya?
> > tinggal di console log fungsi yang pak @mimamch terangkan diatas, pake yang remoteJID <img alt="image" width="418" src="https://user-images.githubusercontent.com/61114044/263925282-9cc64cf3-45d5-41b5-af65-d9af0da0392d.png">
> 
> saya ada wa-gateway juga yang kirim ke group pake @g.us bisa ke kirim, karena groupnya defaultnya itu [nomorpembuat_idgroup@g.us](mailto:nomorpembuat_idgroup@g.us) bukan yang format sekarang, yg pak @jenilutfifauzi test

oh gitu ya?

**Comment by mdestafadilah** [comment]
> > > > > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> > > > 
> > > > 
> > > > sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...
> > > 
> > > 
> > > pake service WA yang lain gimana maksudnya?
> > > tinggal di console log fungsi yang pak @mimamch terangkan diatas, pake yang remoteJID <img alt="image" width="418" src="https://user-images.githubusercontent.com/61114044/263925282-9cc64cf3-45d5-41b5-af65-d9af0da0392d.png">
> > 
> > 
> > saya ada wa-gateway juga yang kirim ke group pake @g.us bisa ke kirim, karena groupnya defaultnya itu [nomorpembuat_idgroup@g.us](mailto:nomorpembuat_idgroup@g.us) bukan yang format sekarang, yg pak @jenilutfifauzi test
> 
> oh gitu ya? pake apa bang?

whatsapp-web.js

**Comment by jenilutfifauzi** [comment]
> > > > > > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> > > > > 
> > > > > 
> > > > > sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...
> > > > 
> > > > 
> > > > pake service WA yang lain gimana maksudnya?
> > > > tinggal di console log fungsi yang pak @mimamch terangkan diatas, pake yang remoteJID <img alt="image" width="418" src="https://user-images.githubusercontent.com/61114044/263925282-9cc64cf3-45d5-41b5-af65-d9af0da0392d.png">
> > > 
> > > 
> > > saya ada wa-gateway juga yang kirim ke group pake @g.us bisa ke kirim, karena groupnya defaultnya itu [nomorpembuat_idgroup@g.us](mailto:nomorpembuat_idgroup@g.us) bukan yang format sekarang, yg pak @jenilutfifauzi test
> > 
> > 
> > oh gitu ya? pake apa bang?
> 
> whatsapp-w

**Comment by horasjey** [comment]
> > > untuk kirim ke grup betul ini ya : [nomerpembuat_idgroup@g.us](mailto:nomerpembuat_idgroup@g.us) bisa dicek remoteJid nya saat menerima pesan masuk di grup
> > 
> > 
> > sudah sesuai pak. saya test pake service wa lainnya, masuk. cuman yang punya pak imam, selalu warning something wrong blablabla...
> 
> pake service WA yang lain gimana maksudnya?
> 
> tinggal di console log fungsi yang pak [@mimamch](https://github.com/mimamch) terangkan diatas, pake yang remoteJID <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/61114044/263925282-9cc64cf3-45d5-41b5-af65-d9af0da0392d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg5MjM2MzYsIm5iZiI6MTczODkyMzMzNiwicGF0aCI6Ii82MTExNDA0NC8yNjM5MjUyODItOWNjNjRjZjMtNDVkNS00MWI1LWFmNjUtZDlhZjBkYTAzOTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA3VDEwMTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTZmNDhlZTY3MWE1ZjI5NWNiN2NjMDY1Mjc1MWRlY2Q2YjcyMzNkZGVjMmNiMDc3MjVmNmRiMzAzYTkyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n37AQT_7PbmMiXdAkuZc6rUIxmnl0Tz_3TEYr6JUsGQ">

maaf pak, bagaimana ya cara buat log console pesan masuk..?
mohon infonya pak
