### ISSUE TITLE
error on deployment, when input number with 62

### ISSUE THREAD

**Issue by galangw** [mimamch/wa-gateway#3]
{
    "status": false,
    "data": {
        "error": "Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined."
    }
}

**Comment by galangw** [comment]
tetap mas

**Comment by mimamch** [comment]
> tetap mas

udah fixed untuk awalan 62, coba lihat kodenya

**Comment by galangw** [comment]
iya mas, udah ternyatatadi lupa restart, itu sama yang +62 mas yang direturn masih final number , sama izin fork ya mas🙏

**Comment by mimamch** [comment]
> iya mas, udah ternyatatadi lupa restart, itu sama yang +62 mas yang direturn masih final number , sama izin fork ya mas🙏

siap
