### ISSUE TITLE
How send image or video?

### ISSUE THREAD

**Issue by zeyn4loff** [mimamch/wa-gateway#38]

**Comment by kikuKeii** [comment]
Hello, let me answer this issue

Based on [wa-multi-session](https://github.com/mimamch/wa-multi-session)

To send an image use the following code
```js
const image = fs.readFileSync("./myimage.png"); // return Buffer
const send = await whatsapp.sendImage({
  sessionId: "session1",
  to: "6281234567890",
  text: "My Image Caption",
  media: image, // can from URL too
});
```
To send an video use the following code
```js
const video = fs.readFileSync("./myvideo.mp4"); // return Buffer
const send = await whatsapp.sendVideo({
  sessionId: "session1",
  to: "6281234567890",
  text: "My Video Caption",
  media: video, // can from URL too
});
```
Image and video sources can also be provided with CDN URLs as long as they can be accessed by the public

**Comment by kikuKeii** [comment]
sorry it might be confusing.
because in this project there is no function and route to send images and videos. You have to create a new function in the controller and create a route that runs the function you created.

**Comment by yromea** [comment]
could you help sending the document i tried to send any type of documents with no luck at all ,
i'm using wa-gateway  tried to modify code of index.js

**Comment by mimamch** [comment]
Send image and documetn was addded on latest version: https://github.com/mimamch/wa-gateway/commit/28082475c07cfbb424931eaa995dd49e67b23136
