### ISSUE TITLE
Error for New Installations

### ISSUE THREAD

**Issue by sricsccenter** [mimamch/wa-gateway#41]
Only Showing Like this 
{
    "message": "phone number must start with valid country code"
}

I tried on my localmachine , Server and all parameters sending as POST and Get nothing works

only showing like this

Test URL: http://localhost:5000/send-message?session=mysession&to=919700000158&text=hi
Response: 
{
    "message": "phone number must start with valid country code"
}

Please Give me any ideas to overcome this problem.

**Comment by mimamch** [comment]
Seems like "91" is not registered as valid country code on "wa-multi-session" library.

**Comment by renandatta** [comment]
i got same problem, any solution yet ?

**Comment by sricsccenter** [comment]
> i got same problem, any solution yet ?

Yes, I found a Solution to Use older Version of Wa-gateway. Exact version that working for me is Below.
Package.json below code and Run Again Run NPM installation.
{
  "name": "wa-gateway",
  "version": "3.2.1",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js --ignore ./wa_credentials --ignore ./public",
    "production": "node server.js -- --staging"
  },
  "author": {
    "name": "mimamch",
    "email": "mimamch28@gmail.com"
  },
  "license": "ISC",
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "dotenv": "^16.0.0",
    "ejs": "^3.1.8",
    "express": "^4.18.2",
    "http-errors": "~1.6.3",
    "moment": "^2.29.4",
    "morgan": "~1.9.1",
    "qrcode": "^1.5.1",
    "wa-multi-session": "3.2.1"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:mimamch/wa-gateway.git"
  }
}

**Comment by renandatta** [comment]
Thank you, it worked

**Comment by mimamch** [comment]
Fixed on latest version: https://github.com/mimamch/wa-gateway/commit/28082475c07cfbb424931eaa995dd49e67b23136
