### ISSUE TITLE
Sending to Group

### ISSUE THREAD

**Issue by mdestafadilah** [mimamch/wa-gateway#8]
Does this API support this?

**Comment by mimamch** [comment]
use this package for advance usage [wa-multi-session](https://github.com/mimamch/wa-multi-session)

**Comment by mdestafadilah** [comment]
oke baik. ini masih pake server @s.whatsapp.net ya? bukan @s.us

**Comment by mdestafadilah** [comment]
nanti saya buat PR untuk routes ke */send-message-group* ya pak.

**Comment by horasjey** [comment]
> nanti saya buat PR untuk routes ke _/send-message-group_ ya pak.

mohon bantuannya pak, cara send ke grup ^_^
