### ISSUE TITLE
delay is not defined

### ISSUE THREAD

**Issue by ilhamlutfi** [mimamch/wa-gateway#9]
{
    "session": "test1",
    "data": [
        {
            "to": 6288***,
            "text": "Hello user 1",
            "delay": 0
        },
        {
            "to": 6288***,
            "text": "Hello user 2",
            "delay": 1000
        }
    ]
}

Is my Postman request correct or is there something wrong, and how do I send a request for bulk messaging?

**Comment by mimamch** [comment]
Sorry for being confusing, I think it's the time for refactoring my code.



> { "session": "test1", "data": [ { "to": 6288***, "text": "Hello user 1", "delay": 0 }, { "to": 6288***, "text": "Hello user 2", "delay": 1000 } ] }
> 
> Is my Postman request correct or is there something wrong, and how do I send a request for bulk messaging?

**Comment by ilhamlutfi** [comment]
Thanks, it's great waiting for it

**Comment by mimamch** [comment]
Hi, I have updated the code. Please pull your code to latest commit.

Here is examples for sending bulk messages

POST /send-bulk-message

`
`

**Comment by mimamch** [comment]
Hi, I have updated the code. Please pull your code to latest commit.

Here is examples for sending bulk messages

POST /send-bulk-message

`
{
"session":"dev",
"delay" : 10000,
"data": [
    {
      "to": "628xxxx",
      "text": "TESTING1"
    },
    {
      "to": "628xxxx",
      "text": "TESTING2"
    },
    {
      "to": "628xxxx",
      "text": "TESTING23"
    },
    {
      "to": "628xxxx",
      "text": "TESTING24453"
    },
    {
      "to": "628xxxx",
      "text": "TESTING2445"
    },
    {
      "to": "628xxxx",
      "text": "TESTING256234234"
    },
    {
      "to": "628xxxx",
      "text": "TESTING234242424234324"
    }
  ]}
`

**Comment by ilhamlutfi** [comment]
Big thanks bro... nicely run
